services:
  - type: web
    name: medoptix-ai-optimizer
    runtime: python
    buildCommand: |
      pip install -e .
      mkdir -p models
    startCommand: uvicorn medoptix_ai_treatment_optimizer.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    healthCheckPath: /
    autoDeploy: true 