services:
  - type: web
    name: medoptix-ai-optimizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    healthCheckPath: /
    autoDeploy: true 